### ISSUE TITLE
Lab 1 - Ex 3 - Task 5 issue

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#10]
# Module: 01
#### Step: 15

Description of issue

Accurately followed all the steps, but not obtaining the desired result while running the Test for Custom Sensitive info types:
![image](https://user-images.githubusercontent.com/6410720/127057291-d5e7734f-54d8-423b-b8f2-170eef8e03cf.png)

Repro steps:

1. Select Documents from the left pane, select the file with the name SickTestData and select Open.
1. Select Test to start the analysis.
1.On the Match results page, review the found match.

**Comment by bneeb** [comment]
If during exercise 3 task 1 step 12, if you didn't enter "Employee" on one line and "ID" on the next line you won't get any results.  I have updated the instructions in step 12 to better explain that.
