### ISSUE TITLE
Lab 1 - Exercise 3 - Task 3 Issue

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#11]
# Module: 1
#### Step: 25

Description of issue
While running the command from step 25, students obtain the following error message:
![image](https://user-images.githubusercontent.com/6410720/127059966-12b024f1-14c5-49de-a088-b9c3f85f82fb.png)

There seems to be some sort of transient error or a delay, the schema can be seen on the UI but while running the command, the schema can not be found.
I waited 48 hours and rerun the command, worked fine. Any way to force a sync?
![image](https://user-images.githubusercontent.com/6410720/127059843-c2ecfefb-e6e8-47ce-8a89-01020f1a2ee3.png)

Repro steps:

1.Download the database schema definition of the EDM-based classification sensitive information type by running the following script in PowerShell:

.\EdmUploadAgent.exe /SaveSchema /DataStoreName employeedb /OutputDir "C:\Users\Admin\Documents\"

**Comment by bneeb** [comment]
I just tested this step 25.  It fails if I login as MOD Admin but it works just fine if I login as JoniS as the instructions state.  Make sure JoniS has been assigned the Compliance role from the first lab and that has propagated.

**Comment by bneeb** [comment]
Commented above.  Can't recreate when following the instructions as stated.
