### ISSUE TITLE
Instructions aren't covering exporting Core eDiscovery Search results, just the "search" itself

### ISSUE THREAD

**Issue by paulschnack** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#14]
# Module: 03
#### Step: 06

Description of issue

To actually export data that's been discovered, the instructions should start on Step 6 and follow on:

Click on the Mark 8 Project Search to open it. 
Click on Actions, select Export results.
In Output options, review the available options and leave the default of All items, excluding ones that have....
Scroll down and click on Export. 
Close the Mark 8 Project search with the cross in the top right corner.
Click on the Exports tab.
Click on Mark 8 Project_Export
Scroll down to the Export key section and click on Copy to clipboard
Scroll back up and click on Download results
Click on Open for installing the Microsoft Office 365 eDiscovery Export Tool, then click Install. 
In the dialog that appears paste the export key into the key field and select the Downloads folder for the export file. Click on Start. 
Open the downloaded folder to review the search results and summary. 

Also, to have the correct permission, Task 2, after step 8 needs to add Joni Sherman to the eDiscovery Manager role:

In Permissions, select eDiscovery Manager.
Next to eDiscovery Manager, click on the blue Edit.
Click Chose eDiscovery Managers, click +Add and add Joni Sherman, click on Done, Save and Close. 

Repro steps:

1.
1.
1.

**Comment by bneeb** [comment]
You are correct.  There was a problem with that lab in the past.  The lab steps have been updated to reflect the proper export steps.  Thank you.
