### ISSUE TITLE
Compliance Manager Interface & Actions Updated - lab needs revising

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#141]
Lesson 4, Lab 4 Ex 1 needs to be updated to match the updated Compliance Manager for navigation and manual/automatic testing changes.

**Comment by riswinto** [comment]
@sarajfMCT, Thank you for bringing this to my attention! The Compliance Manager lab has been updated.
