### ISSUE TITLE
Trainer Prep Guide - Course Timing

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#143]
[SC-400T00A-ENU-TrainerPrepGuide.pdf](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/files/13810153/SC-400T00A-ENU-TrainerPrepGuide.pdf)

Hello 

The Trainer Prep Guide is dated October 2022 - over a year ago. 

The course chapters for the end of Day 1 are duplicated at the start of Day 2. I suspect this has been like this since October 2022. 

The exercises are also out of order which is very confusing to all concerned, especially since the students are not provided with the proper order of exercise execution that is detailed in the Trainer Prep Guide. 

Can we please address these issues as soon as possible? 

Thank you.

**Comment by riswinto** [comment]
Hi @arnoldvilleneuve! Thank you for bringing this to my attention, and I apologize for the confusion these errors have caused. I'll get working on making updates to this ASAP and respond via this issue once the corrected Trainer Prep Guide is published.

**Comment by arnoldvilleneuve** [comment]
Even though I went through the order of the lab/exercises with five students, even though I had them copy my PowerPoint slide in which I detail the order the lab/exercises should be done in (1-3-4-2-5), even though I repeated it two them several times, even though I told them only to do lab/exercise 1 only, two of the 5 still moved to lab/exercise 2!!!
This is what happens when the Instructions and Lab sequence order are not correct. 
Arnold Villeneuve 613-833-0984 

    On Tuesday, January 2, 2024 at 10:43:10 a.m. EST, Richelle Swinton ***@***.***> wrote:  
 
 


Hi @arnoldvilleneuve! Thank you for bringing this to my attention, and I apologize for the confusion these errors have caused. I'll get working on making updates to this ASAP and respond via this issue once the corrected Trainer Prep Guide is published.

**Comment by riswinto** [comment]
Hi @arnoldvilleneuve, I apologize for the frustration and confusion the lab sequence has caused. I understand the importance of clear instructions to be able to conduct your class as smoothly as possible. I'm in the process of reordering the Trainer Prep Guide and labs to match the order that's reflected in the learn paths and PowerPoint deck. To minimize disruption, this change will be implemented after hours and may cause a temporary outage with SC-400 labs. My goal is to have this complete by 9pm CST. I'll respond in this issue to let you know once the labs have been successfully reorganized. 

Thank you for your patience and understanding.

**Comment by riswinto** [comment]
The lab order within Skillable and GitHub have been updated and this has been reflected in an updated Trainer Prep Guide and documented in the change log. 

Please reach out if you have any further issues.

**Comment by arnoldvilleneuve** [comment]
Jan 3, 2024 - Second day of course. 

Dear RISWINTO

I would just like you to know that your update to the Trainer Prep Guide on the night of Jan 2, 2024 (first day of course) caused an entire update of all of the labs on Skillable, labs which are very different than the pervious version of the lab instructions, both in sequence and in content. 

My question is very simple: For what possible reason would a Course Content  Author trigger a course update in the middle of the week that causes a massive change to a course such that on the second afternoon of the course we need to have students start all of the labs all over again? 

The issues I identified were minor compared to the update that was just triggered! 

I look forward to your follow-up and explanation but please do not that the update has caused us significant inconvenience and embarrassment to Skillable and the MTP in question, as well as myself. 

Sincerely; 

Arnold Villeneuve 

PS: Note to Microsoft: Please stop updating courses in the middle of the week as you are not helping anyone.
