### ISSUE TITLE
EDM Classifier Tab does not appear in Lab1/Ex3/Task2/Step23

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#144]
# Module: 01
#### Step: 23

Description of issue: EDM Classifier Tab does not appear - EVER!

This happened for 3 of the 6 students. 

Here is the reply and workaround from Skillable. 

Morgan Gibson (Skillable)

Jan 2, 2024, 6:49 PM EST

Hello Arnold,
 
Our investigation so far shows that the missing "EDM classifiers" tab issue occurs on certain tenants from lab launch. A workaround is not currently available. This issue will be escalated internally in order to coordinate with the Microsoft content owner regarding a resolution. We will update this ticket when additional information is available.
 
Therefore, per your request, we have unassigned the existing tenants from each of the three affected students (Serge, Tade, and Lauren) and we have relaunched new lab instances on their behalf. These instances are currently running and should be available for you to access via the class monitoring feature. Please let us know if you have any difficulties in connecting so that we may assist.
 
Your patience is appreciated. We understand that this tenant issue represents an undesirable interruption to your class. Please feel free to send any additional questions or requests.
 
Best regards,
 
Morgan G | Application Support Administrator
![Lab1-Ex3-Task2-Step23 Not Working](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/edd1f41a-2d07-474c-a0f2-88dc0a61d4e8)

Repro steps:

1.
1.
1.

**Comment by riswinto** [comment]
@arnoldvilleneuve, Thank you for bringing this to my attention. This appears to be an issue with how labs are hosted and will work the hosting provider to see how this issue can be resolved.
