### ISSUE TITLE
MOD Administrator - Not all students have Circle MA as their profile icon in the top right corner of the browser

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#145]
Some students have a celebration horn
![SC-400 MOD Administrator profile icon](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/433fdc2e-744e-411d-9edc-b5a39538e0e3)
. See attached image. .

**Comment by riswinto** [comment]
@arnoldvilleneuve Thank you for bringing this to my attention. I've been unable to reproduce this behavior, but will keep an eye open for if this continues to be an issue.

**Comment by arnoldvilleneuve** [comment]
This issue was closed the day after I opened it yet the problem remains today Feb 27 2024. Why is the Course Author closes cases when they have not been addressed. This kind of information is helpful when they remain open so Students doing the labs on their own can read them.
