### ISSUE TITLE
URL is not correct

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#146]
# Module: 1
#### Step: 16

Description of issue: URL is incorrect. 

![SC-400 Lab1-Ex1-Task1-Step16 URL is incorrect](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/289ea291-a776-454c-9007-981777064199)

**Comment by riswinto** [comment]
@arnoldvilleneuve Thank you for bringing this to my attention. This link has been updated.
