### ISSUE TITLE
User & Admin descriptions are the wrong way around. 

### ISSUE THREAD

**Issue by paulschnack** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#15]
# Module: 03
#### Step: 06

Also, Task 1, Step 14 is the same. 

Description of issue

The order of the User & Admin descriptions are the wrong way around for how they are in the UI - it doesn't affect the outcome of the labs and an attentive student will see the discrepancy but all the other labs have the instructions matching the flow in the UI. 
In Step 6 & 14, simply put the User descriptions before the Admin descriptions. 

Repro steps:

1.
1.
1.

**Comment by bneeb** [comment]
Yes, good catch.  I have made the update to the content in a pull request that will be merged later today.
