### ISSUE TITLE
Course Lab Instructions Totally Updated the after the first day of a four day course!!!!!

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#150]
Jan 3, 2024 - Second day of course.

Dear RISWINTO

I would just like you to know that your update to the Trainer Prep Guide on the night of Jan 2, 2024 (first day of course) caused an entire update of all of the labs on Skillable, labs which are very different than the previous version of the lab instructions, both in sequence and in content.

My question is very simple: For what possible reason would a Course Content Author trigger a course update in the middle of the week that causes a massive change to a course such that on the second afternoon of the course, we need to have students start all of the labs all over again with a fresh VM and O365 Tenant?

The issues I identified were minor compared to the update that was just triggered!

I look forward to your follow-up and explanation but please do not that the update has caused us significant inconvenience and embarrassment to Skillable and the MTP in question, as well as myself.

Sincerely;

Arnold Villeneuve

PS: Note to Microsoft: Please stop updating courses in the middle of the week as you are not helping anyone.

**Comment by riswinto** [comment]
@arnoldvilleneuve, Thank you for bringing this to my attention. I apologize for the inconvenience this caused your class. In the future labs will only be updated on Friday afternoons to avoid this type of disruption.
