### ISSUE TITLE
Lynn Robins user needs password change instructions as well. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#151]
When you have the Students change the Joni user password you should have them do the same for Lynn Robins at the same time.

**Comment by riswinto** [comment]
@arnoldvilleneuve, Thank you for your feedback. Resetting Lynne's and Megan's password is noted in Lab 0, step 10 in the task to set passwords for lab exercises.

**Comment by arnoldvilleneuve** [comment]
Yes, but in Lab 0 Students have NO IDEA how to do that and you simply can't assume they will know to do so later. Nor do you tell them specifically how to update the passwords in Lab 0. They are called Instructions for a reason. 
With all due respect, I have authored seven four and five days courses in my life. If you expect a Student to do something don't assume they know how to do so. Be specific and purposeful in your Instructions. If you want them to change a User password then provide them with the steps to do so at the appropriate point and time in the exercise that you require them to do so, please! 
My recommendation is that you give them the instructions to change all three User account passwords in Lab 0 and get it over with. And perhaps tell them to 1) use the same password for all three Users and 2) tell them to write down the password in case they forgot it on Day 2, which they do. 
This is my first time delivering this course and I entered it when there were NO ISSUES listed in GitHub. As we have seen, that is the furthest thing from the truth. As Course Content Owner we Instructors expect you to keep the course up to date or transfer it to someone that can. Otherwise, we end up in situations like has been caused this week. 
Sincerely; 
Arnold Villeneuve 613-833-0984 

    On Wednesday, January 3, 2024 at 03:44:29 p.m. EST, Richelle Swinton ***@***.***> wrote:  
 
 


@arnoldvilleneuve, Thank you for your feedback. Resetting Lynne's and Megan's password is noted in Lab 0, step 10 in the task to set passwords for lab exercises.
