### ISSUE TITLE
Lab3-Ex4-Task3-Missing Step 14 - Click Close button.

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#154]
![Lab3-Ex4-Task3-Missing Step 14 - Click Close button](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/c5eee4bf-b427-4ac7-b621-104aeb4161fb)

See image

**Comment by riswinto** [comment]
Thank you for bringing these observations to my attention. I'll take them into consideration as part of Friday afternoon's update.
