### ISSUE TITLE
Lab5-Ex3-Task2-Step5 - Required FQDN

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#155]
![Lab5-Ex3-Task2-Step5](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/fcf48424-89a5-4e3d-a6df-620b4c829829)

Please see image. 

Please leave the issue open until it has been addressed and the changes pushed out into production at the Lab Hosting Provider level. To do otherwise is very misleading.

**Comment by riswinto** [comment]
Thank you for this feedback. I'll take this feedback into consideration for the next set of updates

**Comment by arnoldvilleneuve** [comment]
Thank you for your consideration. 
Arnold Villeneuve 613-833-0984 

    On Friday, January 5, 2024 at 05:47:54 p.m. EST, Richelle Swinton ***@***.***> wrote:  
 
 


Thank you for this feedback. I'll take this feedback into consideration for the next set of updates
