### ISSUE TITLE
SC-400 - Into the Breach Once More

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#160]
Hello Again Course Author 

Back in the first week of January, I delivered your course. A mid-week updated caused a lot of serious issues for the students because the update to the labs caused a lot of serious issues. In fact, mid day of the second day we had to get all students started on the course over again! 

Then, throughout the rest of the course I provided feedback on course lab issues and you removed these issues as soon as you read them. The issues were still outstanding while I was teaching the course but they were closed hours after I opened them but before they were actually updated within the actual course lab load itself. 

As I step up to the plate to deliver your course once again I sincerely request that you take a different approach this time: 

1. Do not post a course lab update mid-week please as it really messes up the week! 

2. Do not close Issues that I open during the week while I am teaching the course until a) you have actually fixed them and b) actually tested them and c) then uploaded the new course labs and tested them as well as we both know it is not the responsibility of the Lab Hosting Provider to test your labs to ensure they work and not is it the Instructors and it is certainly not the Paying Students either. 

3. Please keep the Lab Issues that are actually opened until they are fully resolved. We are told by Microsoft through the Lab hosting Provider to show the Students the SC-400 Github Repository before they do any of the labs so they can see if there are any outstanding issues. The last time I delivered SC-400 you were actually closing open Issues during the week we were teaching before the course was done and certainly before the issues were fixed. This is a very important issue because the week after the course some of the Students will actually be doing the course labs again and if you have Closed all of the Issues and they have not actually been fixed by the Lab Hosting Provider then they will not be helped by your doing so. 

I sincerely hope this message gets through to yourself and the Product Manager. Please do not close Lab Issues that are opened by Instructors until they are actually resolved and tested in production. 

Thank you for your attention to this important matter. 

Arnold Villeneuve

**Comment by riswinto** [comment]
Thank you for your feedback. Lab updates will be planned for Friday afternoons going forward. Your insights will be considered carefully in our ongoing efforts to improve the course.
