### ISSUE TITLE
First Page of Labs - Pink Boxes

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#161]
The first Lab 1 page (Pink Boxes) has not been updated since the lab order was changed mid course the week of Jan 5th - when I was in the middle of delivering it! 

It states at the bottom of the Instructions page that Exercise 4 only can complete Task 1 because the Trainable Classifier takes 7 to 14 days to process and that the student should complete the lab after the course is over. 

However, this lab is now Exercise 3 as a result of the mid week course load update. 

![Lab 1 Exercise 4 is now Exercise 3](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/1082625/ad6ec704-a4e8-411d-b264-fe94d5ec2e00)

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. It appears this was resolved by the lab hosting provider, but I'll get with them to verify before I close this issue.

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. This box is no longer displayinh
