### ISSUE TITLE
MA (user) in top right corner 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#162]
# Module: 1
#### Step: 17.....

On the Audit page. select Start recording user and admin activity to activate audit logging.

Select the circle with MA in the upper right and select Sign out.

Close the Microsoft Edge browser window.

Description of issue

There is no MA for the MOD Administrator. It is a trumpet or speaker cone. 

This issue was already reported back on Jan 5th but was closed by the Course Author even the issue still exists and has not been addressed in the production load of the classroom. 

Repro steps:

1.
1.
1.

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. This has been updated.
