### ISSUE TITLE
Lab 2 - Exercise 2 - Manage Endpoint DLP

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#164]
# Module:2

### Task: 4
Step 3 In the Microsoft Purview portal, on the left navigation pane, expand Data loss prevention then select Endpoint DLP Settings.

 Endpoint DLP Settings is now Data Loss Prevention Setting link in  upper right

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. This has been updated.
