### ISSUE TITLE
Lab 3 Ex 1 - Retention Policies - Adaptive scopes access

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#166]
#### Step: 3

Description of issue

Even with E5 license assigned, neither Joni or the MOD admin account in my tenant seem to have access to adaptive scopes area (screenshot attached). Has access to this area changed? What permissions/license is required?

![image](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/114931569/b2656371-d606-405a-b71b-b4bbcfd16ff0)

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. I was not able to replicate this issue, however this might be specific to GoDeploy labs. I'll work with the lab hosting provider to further investigate the issue.

**Comment by SkillableKA** [comment]
Hello,

We are also getting reports of users experience this issue. I have been able to reproduce the error using both the JoniS account, as instructed, as well as the MOD Administrator account.

![image](https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/assets/169093291/0f033c82-047e-47ee-8c5c-6814ae64a6ba)

**Comment by riswinto** [comment]
@SkillableKA, @LewisGoDeploy, @ArturoBravo111, We're still investigating this issue with the tenant to understand why Adaptive scopes are no longer working in SC-400 labs. I've made the decision to remove this task from labs until we can get this resolved. I'll need to remove this on Friday to not disrupt any possible on-going classes. I'll keep you all posted on when we can resolve this issue.

**Comment by riswinto** [comment]
Tasks 4 and 5 from Lab 3 exercise 1 have been removed until this issue can be resolved.

**Comment by riswinto** [comment]
@ArturoBravo111, @LewisGoDeploy, @SkillableKA, this issue has been resolved. I'm bringing adaptive scope labs back into SC-400 today for trainers to train on this topic next week.
