### ISSUE TITLE
Trainable Classifier Procedure

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#169]
# Module: 01
#### Step: 12

Description of issue

You can only select a maximum of10 SharePoints.

Also, you will then be prompted to select negative SharePoint sites.  This will require an additional step in Task3.  If you just select an existing SharePoint site, it will result in an error message when the trainable classifier carries out it's training.  The status message returned is:  InvalidLocationsError

Repro steps:

1.
1.
1.

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. The Trainable Classifiers lab has been updated.
