### ISSUE TITLE
Information Barrier Processor  invalid AppId.

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#170]
# Module: 00
#### Step: 6

Description of issue

When trying to register the Information Barrier Processor app with the well known App Id of bcf62038-e005-436d-b970-2a472f8c1982 you receive an error message stating that the App Id is invalid.

Repro steps:

1. Connect-AzureAD -Tenant "WWLxZZZZZZ.onmicrosoft.com"
2. $appId="bcf62038-e005-436d-b970-2a472f8c1982"
3. New-AzureADServicePrincipal -AppId $appId

4. Error Message in PowerShell:  The appId 'bcf62038-e005-436d-b970-2a472f8c1982' of the service principal does not reference a valid application object.

Fix:

Ignore the error and carry on with the exercise.

I was able to define segments, modify users properties so they got assigned to segments.  Next, configure the M365 Groups used by MS Teams for Information Barrier Implicit mode and demonstrate that users in incompatible segments could not communicate with each other.  It took just under 24 hours for the users to be assigned to a segment.

**Comment by hafometh88** [comment]
I had the same issue.

**Comment by riswinto** [comment]
@LionelShaul and @hafometh88, thank you both for bringing this to my attention. It appears that enabling admin consent for information barriers in Teams is no longer necessary, so Task 2 has been removed from this lab.
