### ISSUE TITLE
Microsoft Exchnage Retention Policies

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#171]
# Module: 00
#### Step: 00

Description of issue:  If a mailbox doesn't have a retention tag policy applied,  in-place archiving will not occur even if in-place archiving is enabled.  This makes sense because you need to supply the managed folder assistant with instructions as to what to archive.  The default mailbox retention tag in the retention tag policy provides the instructions as to what to archive. Exchange Mailbox Retention tags and Retention tag policies are now managed in Purview.  This should be added to the course material.  I am sure this has mystified many people (including myself).

Repro steps:

1. Enable in-place archiving for a mailbox.
2. No messages get archived.
3. Then apply a retention tag policy to the mailbox.  Notice that archiving begins.

**Comment by riswinto** [comment]
@LionelShaul, Thank you for this feedback! I do have plans to update data lifecycle and records management content by the end of this year, so I'll keep this in mind for both SC-400 and SC-5007.

**Comment by LionelShaul** [comment]
Hi Richelle:

 

In my consulting practice, I am noticing that users whose mailboxes have been migrated from on-premises are the ones that don’t have any default retention tags so when you go to enable archiving, nothing happens because the managed folder assistant doesn’t know what to do.  Rather than tags, if there is just a retention policy set in Purview for the mailbox, would this fix the problem.? I would have to test that.

 

I really appreciate your feedback as well!

 

Best regards,

 

Lionel

**Comment by LionelShaul** [comment]
Hi Richelle:

 

For email accounts that are created new in M365 rather than from synchronization via Entra Connect, the mailboxes do have a Default MRM policy automatically assigned so archiving will work as expected.

 

Best regards,

 

Lionel
