### ISSUE TITLE
Labs Topic "Manage Trainable Classifiers" instructions are not given up to the point. 

### ISSUE THREAD

**Issue by dparekh1994** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#173]
# Module: 00
#### Step: 00

Description of issue:

Point 1- Student are able to create Custom Trainable Classifiers whethere on labs its mentioned to wait for 14 days for this activity. 
Point 2- Steps to upload Positive and Negative samples is missing. 
Point 3- As per Labs instructions SharePoint sites needs to be included as samples, but some sites does not display in the list.
Point 4- Even Github Document has similar details: 
https://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator/blob/master/Instructions/Labs/LAB_AK_01_Lab1_Ex3_Trainable_Classifiers.md

Repro steps:

1.
1.
1.

**Comment by riswinto** [comment]
Thank you for bringing this to my attention. The Trainable Classifiers lab has been updated.
