### ISSUE TITLE
"Enable self-service password reset" doesn't appear to be in the list of improvement actions

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#188]
#### Step: 05

Description of issue
"Enable self-service password reset" doesn't appear to be in the list of improvement actions after following the guide.

![image](https://github.com/user-attachments/assets/ba203810-3eae-40b9-a7e4-cc7cd8e526a5)

![image](https://github.com/user-attachments/assets/7954ca61-3a88-4787-9903-aa02afa4a33c)

**Comment by riswinto** [comment]
@TesterTesterson1004, I was able to find the **Enable self-service password reset** improvement action in Compliance Manager, but I had to make sure Joni had **Compliance Administrator** access granted from lab 1, exercise 1, task 1 and **Compliance Manager Administrators** access granted in lab 4, exercise 1, task 1. It's possible it takes a moment for permissions to replicate after lab 4, exercise 1, task 1, so I'll add a note that if you're not seeing that improvement action you might have to wait a few minutes.
