### ISSUE TITLE
Exercise 3 - Manage Sensitive Information Types, Task 1, Step 8 

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#2]
# Module: 01
#### Step: 08

Description of issue
Step should say "On the Requirements for matching page, select (+) Create Pattern." instead of "On the Requirements for matching page, select (+) Add an element."
Repro steps:

1. 
1.
1.

**Comment by bneeb** [comment]
Hi,
Thanks for pointing this out.  The M365 tenant that ships with the course just had a refresh the first week of May.  These steps changed as you noted with that refreshed tenant.  The steps have been adjusted as you suggest in Exercise 1.

**Comment by bneeb** [comment]
closing issue now that it's resolved in the repo.

**Comment by LodsCory** [comment]
Sorry I'm late responding. Thank you!
