### ISSUE TITLE
Missing sites required for Exercise 4 

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#25]
# Module: 01
#### Step: 12

Description of issue

Repro steps:

Task 2 – Create a trainable classifier
10. Select Next.

11. Select Choose sites to open the right side pane.

12. Select the following SharePoint sites:

      Communication site
      News @ Contoso
      Contoso Web 1
      Brand
      Digital Initiative Public Relations
      Work @ Contoso
      Sales and Marketing
      Contoso Landings
      Mark 8 Project Team
      HR
      Operations
      Retail
      PointPublishing Hub Site
      Team Site
      Leadership Team
      Community
      Give @ Contoso
      Benefits @ Contoso
      Learn @ Contoso
      Campaigns - Events
      While followign the following steps:

I found that the following sites are no longer available on new tenants:

    - PointPublishing Hub Site
    - Team Site
    - Community
    - Give @ Contoso
    - Benefits @ Contoso
    - Learn @ Contoso
    - Campaigns - Events
    
Can we confirm if these can be added?, otherwise I will adjust the instructions and delete them from the instructions as it can be misleading to learners.

**Comment by bneeb** [comment]
Hi Cristian,
I've noticed you need to be logged in as Jodi Sherman in the tenant to see those SharePoint sites.  I just fetched a classroom tenant last week for testing and it has those sites, but they only appear when signed in as Jodi not Admin.  See image below.
![image](https://user-images.githubusercontent.com/12865697/142701749-be5a57ea-3f93-4713-9daa-06bac1263295.png)
