### ISSUE TITLE
SC-900 IRM OEM test

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#3]
# Module: 01
#### Step: 14
Description of issue - TestIRMConfiguration Fails either with -confirm or -sender switch. Tried this on several trial tenancies - same issue. Also contoso.com is not a verified domain. Even using the onmicrosft tenancy name it still fails. The lab doesn't appear to work regardless but this is confusing and even a support request to MS went no where.

Repro steps:

1. Ignore error and proceed.
1.
1.

**Comment by bneeb** [comment]
Hi, this lab step has been tested many times and never had any issues with the Microsoft 365 tenants issued by authorized lab hosters (ALH) for the course.  My guess is you're using some other trial tenant that does not include the pre-configuration of Contoso among other configuration as the tenants issued by ALHs.
