### ISSUE TITLE
Mod 1 Sensitive Info Types

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#4]
# Module: 01
#### Step: 13

Description of issue- Keyword entries must be on separate lines - no commas between them. The "T" paste places commas in the list.

Repro steps:

13a .Paste the employee,absence,reason entry
13b. Remove the commas and have each keyword on a separate line

**Comment by bneeb** [comment]
You're right, but I'm not going to merge this pull request for a couple reasons:

First, your reference to the "T" button in the lab interface suggests to me you're using Learn On Demands Systems (LODS) for your lab testing.  The auto-load text button in the interface is controlled by LODS and we need them to implement any changes to how there buttons function.

That said, I'd prefer the change to the lab instructions here to read something like "Hint: keyword entries must be on separate lines with no commas."
Adding that hint would help the learner appreciate how delicate the entry for this field is.

Second, you added a number of other changes to the PR to other instructions that need to be validated still.  The tenant pool issued to ALHs is assembled fresh each month.  Typically subtle changes to the UI take place in Microsoft 365 so frequently we try to retest these labs nearly as frequently.  A fresh test of this entire SC-400 lab set is happening in the next couple weeks, we'll validate UI changes at that time.

**Comment by bneeb** [comment]
The lab instructions have been adjusted to more clearly list how the data must be entered into the box.
