### ISSUE TITLE
Mod 3 Retention Policies Powershell

### ISSUE THREAD

**Issue by CallanTurner** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#5]
# Module: 03
#### Step: 01

Description of issue - Says log onto Client 2 VM (LON-CL1) - which is Client 1VM

Repro steps:

1.Log into Client 1 VM (LON-CL1)
1.
1.

**Comment by bneeb** [comment]
Good catch.  PR merged.
