### ISSUE TITLE
Onboarding Devices Grayed Out for Admin

### ISSUE THREAD

**Issue by billy-tarazy** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#60]
# Module: 02
#### Step: 04

Description of issue (  cannot turn on onboarding devices from the settings, it's grayed out and requiring a subscriptions )
![Capture](https://user-images.githubusercontent.com/46200613/184873628-cd26bc73-0622-4726-9b4b-76b8fdec6c65.PNG)

**Comment by riswinto** [comment]
Thank you for bringing this to our attention. 

I was able test device onboarding with Joni's account as the lab instructions are written, and was successfully able to enable device onboarding.

![image](https://user-images.githubusercontent.com/59936978/185710213-5a85b625-9ce0-4c29-9666-62b159913590.png)

![image](https://user-images.githubusercontent.com/59936978/185710235-702a2db0-2101-4755-a214-68260f7a2b20.png)

It’s possible this feature was unavailable for a brief period or there were possible issues with service availability for lab tenants impacting device onboarding.
