### ISSUE TITLE
Student Handbook and AllFiles content link has nothing in it.

### ISSUE THREAD

**Issue by maccaoz** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#63]
When clicking the link in the main repro page for the Student Handbook and All Files, it leads to an empty repo
![All files link](https://user-images.githubusercontent.com/60631691/199596642-d01f3675-5fea-4fa8-9e10-7418047a9c95.png)

**Comment by riswinto** [comment]
Thank you for bringing this to our attention. References to the student handbook have been removed.
