### ISSUE TITLE
Lab 2 - Exercise 2 - Manage Endpoint DLP Task 3 needs a review

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#69]
# Module: 2
#### Step: 20

Description of issue
According to the description and result of the task, we need to create a DLP policy to block copy content from documents that contain credit card info. However, while performing the steps we are blocking Employee ID numbers and diseases from being shared on endpoints.

Also in step 20: "Scroll down to the User overrides section and below Allow override from Endpoint devices, select Copy from clipboard", the **Allow override from Endpoint devices** is not available.

![image](https://user-images.githubusercontent.com/98971092/220136812-ce8e196b-55bc-4ade-bf35-c0c48ff18576.png)

Repro steps:

1. Perform steps till step 20
2. See the difference in UI.

**Comment by riswinto** [comment]
This has been updated. In order to select **Allow overrides from M365 services** the check box for **Notify users in Office 365 service with a policy tip** under **Microsoft 365 services** must be selected. These steps have been updated in the lab.
