### ISSUE TITLE
Lab 3 - Exercise 4 - Configure Event-based Retention Task 4 no option to apply label

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#70]
# Module: 03
#### Step: 08

Description of issue

Hello, I'm unable to see any option to apply the label on the Operations site even after waiting for a few hours, can I get some guidance on what I might be doing wrong? Although the label shows up successfully on other sites see the 2nd screenshot.

![image](https://user-images.githubusercontent.com/98971092/220425873-65e0ef32-f691-4367-81bc-3f497eadbac8.png)

![image](https://user-images.githubusercontent.com/98971092/220426924-f597a02b-7694-4277-8bf9-883b31e369a2.png)

Repro steps:

1. Perform all steps till step 8
1. No option to apply the label shows up.

**Comment by riswinto** [comment]
Thank you for bringing this to my attention, and apologies on the late reply as I was researching this issue. 

I was able to reproduce the same issue, and am this time I'm unsure as to why this retention label was available in some SharePoint libraries and not in others. For now I'll be rewriting this step to apply the retention label to a document that is not in a SharePoint library experiencing this issue while I continue to investigate.
