### ISSUE TITLE
LAB_AK_02_Lab1_Ex2_Endpoint_DLP.md - UI Drift of Block with Override, and a typo

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator#77]
# Module: 2
#### Task: 3

Typo: Change the title of the task from "Create and Endpoint DLP policy" to "Create an Endpoint DLP policy".

UI Drift: The location of the Overrides setting has changed.

**Modify Step 18, replace:**

    Leave all checkboxes enabled and change the dropdown selections on the right from Audit only to Block.

**With:**

    Leave all checkboxes enabled. Change the dropdown selection for Copy to clipboard from App,ky to Block with Override. Change the dropdown selection for all the other items from Audit only to Block.

**Remove Step 22.**

**Comment by riswinto** [comment]
This has been updated. Thank you for bringing this to my attention.
